- name: Merge excludes
  ansible.builtin.set_fact:
    restic_excludes: "{{ restic_specific_excludes | extend(restic_default_excludes) }}"
  when: restic_specific_excludes is defined

- name: Merge excludes
  ansible.builtin.set_fact:
    restic_excludes: "{{ restic_default_excludes | default([]) }}"
  when: restic_specific_excludes is not defined

- name: User backup
  ansible.builtin.import_tasks: user.yml
  when: restic_backup_mode is defined and restic_backup_mode == "user"

- name: Server backup
  ansible.builtin.import_tasks: server.yml
  when: restic_backup_mode is defined and restic_backup_mode == "server"
