- name: user backup
  import_tasks: user.yml
  when: restic_backup_mode is defined and restic_backup_mode == "user"

- name: server backup
  import_tasks: server.yml
  when: restic_backup_mode is defined and restic_backup_mode == "server"
